### ISSUE TITLE
RISC-V CHERI exception priority table doesn't include PCC unaligned base

### ISSUE THREAD

**Issue by bsdjhb** [CTSRD-CHERI/cheri-specification#54]
The table listing the priority of the various conditions raising a capability violation exception for RISC-V doesn't include PCC unaligned base.  (Originally noticed this while working on #27)

**Comment by PeterRugg** [comment]
Hmm, the natural place to put this would be just before length exception. Do we specify where the base ISA "misaligned instruction" exception sits with respect to the CHERI exceptions? Incidentally, it looks like hardware currently throws a "misaligned instruction" rather than a CHERI exception in the misaligned base case.

**Comment by PeterRugg** [comment]
Sail puts it after the bounds check: https://github.com/CTSRD-CHERI/sail-cheri-riscv/blob/52bda608e14cdc2bfd6238ba5918beaebc1ba9b0/src/cheri_insts.sail#L145

That might be annoying in hardware since the bounds check happens a cycle later than the rest. This case will go away without relocation though?

**Comment by arichardson** [comment]
> Sail puts it after the bounds check: https://github.com/CTSRD-CHERI/sail-cheri-riscv/blob/52bda608e14cdc2bfd6238ba5918beaebc1ba9b0/src/cheri_insts.sail#L145
> 
> That might be annoying in hardware since the bounds check happens a cycle later than the rest. This case will go away without relocation though?

We can also move it earlier (even though it's going away)

**Comment by PeterRugg** [comment]
Yeah, I doubt much thought was put into it. I imagine that's the way forward: instruction misaligned -> PCC base misaligned -> out ouf bounds.

**Comment by PeterRugg** [comment]
I've added it here: https://github.com/CTSRD-CHERI/cheri-specification/commit/d2e8d7f2cb2e9ccd037a8d03ba0b6e2c8fb0df9e
